[package]
name = "vktutor-rust"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
#panic = "abort"

[profile.release-lto]
inherits = "release"
lto = true

[dependencies]
vulkano = "0.30.0"
vulkano-shaders = "0.30.0"
winit = "0.26.1"
vulkano-win = "0.30.0"
bytemuck = "1.9.1"
